services:
  uni-api:
    container_name: uni-api
    image: yym68686/uni-api:latest
    environment:
      - USE_ROUND_ROBIN=True
    ports:
      - 8001:8000
    volumes:
      - ./api.yaml:/home/api.yaml